### PR TITLE
Cleanup and tests

### PR DESCRIPTION
**Pull request by jerith**
This is very WIP at the moment.

### CODE REVIEW

**Comment by JayH5** [comment]
LGTM, just not sure why all the commented-out stuff is there?

**Comment by jerith** [comment]
> LGTM, just not sure why all the commented-out stuff is there?

Because I'm still writing more tests. :-)

**Comment by JayH5** [comment]
OK well shall we merge this for now? :+1:

**Comment by JayH5** [comment]
:+1:

**Pull request merged**
