### PR TITLE
Use concat to build config

### PR DESCRIPTION
**Pull request by jerith**

### CODE REVIEW

**Comment by jerith** [comment]
Necessary for #8.

**Comment by JayH5** [comment]
LGTM overall, although isn't the real solution to have xylem read multiple config files from a directory?

**Comment by calston** [comment]
:+1:

**Comment by jerith** [comment]
> isn't the real solution to have xylem read multiple config files from a directory?

Perhaps, but that makes the config parsing logic there significantly more complex.

**Comment by calston** [comment]
I have some code for merging a conf.d/*.yml style thing in Tensor, I could just clone that over?

**Pull request merged**
